name: Python application

on:
  push:   
    branches:
      - main
      - feature/deploys3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run application
      run: python criarcsv.py  

    - name: Upload artefato
      uses: actions/upload-artifact@v4
      with:
        name: meu-arquivo
        path: Relatorio-Contabil.csv
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false
  
  aws:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Fazer Download do artifact
      uses: actions/download-artifact@v4
      with:
        name: meu-arquivo
        path: ./meu-arquivo
    
    - name: Configurando as Credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - run: |
        timestamp=$(date +'%d/%m/%Y %H:%M:%S')
        aws s3 cp ./meu-arquivo/Relatorio-Contabil.csv s3://${{ secrets.AWS_BUCKET_NAME }}/Relatorio-Contabil-$timestamp.csv
