name: Python application

on:
  push:   
    branches:
      - main
      - feature/deploys3
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Variavel de ambiente para o nome do arquivo
      run: echo "NOME_ARQUIVO=$(date +'%d-%m-%Y')-Relatorio-Contabil.csv" >> $GITHUB_ENV

    - name: Run application
      run: python criarcsv.py  

    - name: Upload artefato
      uses: actions/upload-artifact@v4
      with:
        name: meu-arquivo
        path: ${{ env.NOME_ARQUIVO }}
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false
  
  aws:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Fazer Download do artifact
      uses: actions/download-artifact@v4
      with:
        name: meu-arquivo
        path: ${{ github.workspace }}
    
    - name: Configurando as Credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Copiando o arquivo para o S3
      run: aws s3 cp ${{ github.workspace }}/meu-arquivo/${{ env.NOME_ARQUIVO }} s3://${{ secrets.AWS_BUCKET_NAME }}

